### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai202-grebenik#10]
https://drive.google.com/file/d/1Jupr5VQFJpOmHJSJY9Vu2JgmrSXgxk2I/view

**Comment by AngelikaGrebenik** [comment]
Завдання 1
1. У потребі "спілкування на теми масової культури" доступність не являється проблемою, бо завжди є у доступі, кожен може поспілкуватися з різними людьми у будь-який час у активному чаті нашого ПП.  Наш ПП повністю задовольняє доступність цією потреби.
2. У потребі "спілкування на теми масової культури" проблеми у зрозумілості немає, бо не викликає жодних запитать при використанні функції спілкування в чаті нашого ПП, він завжди активний. Наш ПП повністю задовольняє зрозумілість цієї потреби
3. У потребі "спілкування на теми масової культури" цінність також не є проблемою, бо спілкування абсолютно безкоштовне та не потребує нічого від користувача. Наш ПП повністю задовольняє у цінності, всіх наших користувачів.

Завдання 2
Метою ПП було забезпечення користувачів водою, у власному житлі через її критичну необхідність для кожної людини
1. Авторизація користувача наближує до досягнення нашої мети тим, що користувач отримав усі можливості для оренди житла, в якому він буде проживати, на наявності функції замовлення води до власного житла, чим і наближує наш ПП до  мети. 
2. Знайти житло наближує до досягнення мети тим, що надає обрати власне житло та оформити договір на його оренду, чим виконує частину мети "власному житлі'
3. Замовити воду наближує до досягнення мети доступністю створити запит на замовлення води, чим забезпечує користувача водою у власному житлі, що і наявне в нашій меті

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
